compile:
	@g++ -I/home/ghait/Desktop/AdventureGame/Game/headers -Wall -g -o main hud.cpp level.cpp main.cpp tile.cpp tinyxml2.cpp sprite.cpp game.cpp input.cpp graphics.cpp animatedSprite.cpp player.cpp animatedtile.cpp -lSDL2 -lSDL2_image
	@./main
	@rm main
